import {Filter} from 'app/screens/program-screen/components/TypeFilter'

export type Talk = {
  timeKey: string
  time: string
  location: string
  title: string
  speakers: string
  type: Filter
}

const schedule: Talk[] = [
  {
    timeKey: '09:15',
    time: '09:15-09:35',
    location: 'Lesesal 1',
    title: 'OKR og hvorfor vi hater det😡',
    speakers: 'Jonas Nouri, Maren Schliekelmann Barth',
    type: 'Tech(lett)',
  },
  {
    timeKey: '09:15',
    time: '09:15-09:35',
    location: 'Foredragsrommet',
    title: 'Brukerinnsikt: ikke glem hvilke verktøy som passer til hva!',
    speakers: 'Linn Harbo Dahle',
    type: 'Design',
  },
  {
    timeKey: '09:15',
    time: '09:15-09:35',
    location: 'Backstage',
    title: 'Learned Indexes: Maskinlæring møter databaseindeksering!',
    speakers: 'Simen Sælevik Tengs',
    type: 'Prosess',
  },
  {
    timeKey: '09:15',
    time: '09:15-09:35',
    location: 'Det turkise rommet',
    title: 'Oppdragsdashboard - fra kul idé til nødvendighet? 🤔',
    speakers: 'Erika Åsberg, Thomas Luzi',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '09:15',
    time: '09:15-11:40',
    location: 'Olavs møterom',
    title: 'Django workshop | Hvorfor jeg elsker Django',
    speakers: 'Emil Telstad',
    type: 'Tech(lett)',
  },
  {
    timeKey: '09:40',
    time: '09:40-09:50',
    location: 'Lesesal 1',
    title: 'Musikals innslag av Vippeklangen 🎶',
    speakers: 'Vippeklangen',
    type: 'Prosess',
  },
  {
    timeKey: '09:50',
    time: '09:50-10:30',
    location: 'Lesesal 1',
    title: '🚨 KATASTROFE: Gjenoppretting av kritisk norsk infrastruktur 🚨',
    speakers: 'Edvard Viggaklev Bakken, Sara Waaler Eriksen',
    type: 'Annet',
  },
  {
    timeKey: '09:50',
    time: '09:50-10:30',
    location: 'Det turkise rommet',
    title: 'Designsystem for flere merkevarer: Prosess og verktøy',
    speakers: 'Halldis Søhoel, Lars Kinn Ekroll',
    type: 'Design',
  },
  {
    timeKey: '09:50',
    time: '09:50-10:30',
    location: 'Foredragsrommet',
    title: 'Hvorfor skal vi tenke på bærekraftig produktutvikling?',
    speakers:
      'Hedvig Berg, Ragnhild Nordgård, Hans Kristian Henriksen, Thea Thorleifsson, Morten Grønvold, Frithjof Frederiksen, Hedda Langvik og Frida Støvern',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '09:50',
    time: '09:50-10:30',
    location: 'Backstage',
    title:
      'Infrastruktur i skyen, med tillit som produkt || 🦀 Rust + WebAssembly i brukerens nettleser 🦀',
    speakers: 'Thomas Oddsund, Kevin Sillerud',
    type: 'Annet',
  },
  {
    timeKey: '09:50',
    time: '09:50-11:40',
    location: 'Direktørrommet',
    title:
      "Psykologisk trygghet i praksis - Det er ikke (bare) 'hvem du er' som betyr noe, det er hva du gjør",
    speakers: 'Ingrid Hjulstad',
    type: 'Prosess',
  },
  {
    timeKey: '10:45',
    time: '10:45-11:05',
    location: 'Lesesal 1',
    title: 'Backend-teamet ditt trenger en designer',
    speakers: 'Herman Slyngstadli',
    type: 'Design',
  },
  {
    timeKey: '10:45',
    time: '10:45-11:05',
    location: 'Det turkise rommet',
    title: 'Felt av Diskrimineringsnemnda',
    speakers: 'Martin Jackson',
    type: 'Soft skills',
  },
  {
    timeKey: '10:45',
    time: '10:45-11:05',
    location: 'Foredragsrommet',
    title:
      'Hjemmebanen for norsk idrett: I stormens øye av TV 2s nye prestisjeprosjekt',
    speakers: 'Tobias Pettrem, Ingrid Karoliussen, Caroline Jenssen',
    type: 'Forretning',
  },
  {
    timeKey: '10:45',
    time: '10:45-11:05',
    location: 'Backstage',
    title: 'Dropp serveren! || Nøkkelløs autentisering fra Github Actions',
    speakers: 'Toralf Christian Skaali Frich, Torgeir Thoresen',
    type: 'Prosess',
  },
  {
    timeKey: '11:20',
    time: '11:20-11:40',
    location: 'Lesesal 1',
    title: 'Er (digital) innovasjon i offentlig sektor annerledes?',
    speakers: 'Yngve Milde',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '11:20',
    time: '11:20-11:40',
    location: 'Det turkise rommet',
    title: '🇩🇰, 🥐, 🚤 og andre hemmeligheter som skaper høytpresterende team',
    speakers: 'Sonja Porter',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '11:20',
    time: '11:20-11:40',
    location: 'Backstage',
    title:
      'Kan jeg låne den minnereferansen? OK, så lenge jeg får den tilbake!',
    speakers: 'Geir Sagberg',
    type: 'Prosess',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Lesesal 1',
    title:
      'Effektmåling med Mixpanel - hvordan unngå å kaste millioner ut av vinduet!',
    speakers: 'Christian Young',
    type: 'Soft skills',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Det turkise rommet',
    title:
      'Mikrotjenester: en smidighetsfelle? || Bevar fatningen til kollegaene dine: Teknikker for meningsbærende kode',
    speakers: 'Robin Heggelund Hansen, Runar Skagestad',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Foredragsrommet',
    title: 'Den gode ChatGPT 🤖',
    speakers:
      'Andreas Heim, Herman Slyngstadli, Bendik Edvardsen, Kehan Mahic, Jens Andreas Huseby',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Backstage',
    title: 'Designtrio (åpne for å se de ulike bidragene)',
    speakers: 'Lukas Aasbø, Frida Støvern, Ruben Kive Horn',
    type: 'Design',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Olavs møterom',
    title: 'Språk & Språk | Design ditt eget programmeringsspråk!',
    speakers: 'Johannes Hoseth Klev',
    type: 'Design',
  },
  {
    timeKey: '12:50',
    time: '12:50-13:30',
    location: 'Direktørrommet',
    title: '"Hvem er du?" - Workshop i Big 5 (personlighetspsykologi)',
    speakers: 'Jarle Svendsrud, June Henriksen, Jørund Amsen',
    type: 'Tech(lett)',
  },
  {
    timeKey: '13:45',
    time: '13:45-14:05',
    location: 'Lesesal 1',
    title: 'Hvordan truserøske en organisasjon på 5 dager',
    speakers: 'Erik Mathisen',
    type: 'Soft skills',
  },
  {
    timeKey: '13:45',
    time: '13:45-14:05',
    location: 'Det turkise rommet',
    title: 'Billettindustriens rebeller',
    speakers: 'Erling Van De Weijer',
    type: 'Soft skills',
  },
  {
    timeKey: '13:45',
    time: '13:45-14:05',
    location: 'Foredragsrommet',
    title: 'Datamesh – det neste store paradigmeskiftet etter DevOps?',
    speakers: 'Simen Holmestad',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '13:45',
    time: '13:45-14:05',
    location: 'Backstage',
    title: 'SVG-magi i OBOS julekalender🎄',
    speakers: 'Håkon Stubhaug Drangsland',
    type: 'Tech(lett)',
  },
  {
    timeKey: '14:25',
    time: '14:25-15:05',
    location: 'Lesesal 1',
    title: 'Slett arbeid',
    speakers: 'Sigbjørn Lund Olsen',
    type: 'Soft skills',
  },
  {
    timeKey: '14:25',
    time: '14:25-15:05',
    location: 'Det turkise rommet',
    title:
      'Orkestrering av distribuerte asynkrone prosesser i en synkron verden || Hva er deterministiske bygg, og hvorfor skal du bry deg?',
    speakers: 'Stig-Rune Skansgård, Andreas Mosti',
    type: 'Tech(lett)',
  },
  {
    timeKey: '14:25',
    time: '14:25-15:05',
    location: 'Foredragsrommet',
    title: 'Når alt raser',
    speakers: 'Kine Asmussen Vaagan',
    type: 'Tech(tungt)',
  },
  {
    timeKey: '14:25',
    time: '14:25-15:05',
    location: 'Backstage',
    title:
      'Er morgendagens vinnere de som tør satse på bærekraft i dag? || En kort guide til hypotesetesting og eksperimenter || Den profesjonelle samtalen - fra erfaringsbasert til forskningsbasert! 🧠',
    speakers:
      'Thea Thorleifsson, Ragnhild Nordgård, Ida Christine Opsahl Høydal',
    type: 'Tech(lett)',
  },
  {
    timeKey: '14:25',
    time: '14:25-15:05',
    location: 'Olavs møterom',
    title: 'Lektor Husebys papirflyhypotesetestingsworkshop',
    speakers: 'Jens Andreas Huseby',
    type: 'Forretning',
  },
  {
    timeKey: '15:20',
    time: '15:20-15:40',
    location: 'Lesesal 1',
    title: 'Datadrevet prestasjon',
    speakers: 'Runar Ovesen Hjerpbakk',
    type: 'Tech(lett)',
  },
  {
    timeKey: '15:20',
    time: '15:20-15:40',
    location: 'Det turkise rommet',
    title: 'Ett år hos OBOS',
    speakers: 'Arne Magnus Mykkelbost, Ingar Mathisen Almklov',
    type: 'Forretning',
  },
  {
    timeKey: '15:20',
    time: '15:20-15:40',
    location: 'Foredragsrommet',
    title: 'Slutt med global state tull! Bruk Tanstack Query for det er gull!',
    speakers: 'Robert Kittilsen',
    type: 'Annet',
  },
  {
    timeKey: '15:20',
    time: '15:20-15:40',
    location: 'Backstage',
    title:
      'Uten kart og kompass hos Kartverket || I Kartverket fører alle veier til juridisk avdeling',
    speakers: 'Magnus Ramm, Magnus Søyland',
    type: 'Annet',
  },
  {
    timeKey: '15:55',
    time: '15:55-16:15',
    location: 'Det turkise rommet',
    title: 'Sikkerhetskultur spiser policy til frokost 🥞☕️',
    speakers: 'Didrik Sæther',
    type: 'Prosess',
  },
  {
    timeKey: '15:55',
    time: '15:55-16:15',
    location: 'Backstage',
    title:
      '10 ting du (kanskje) ikke visste om CSS || Skap verdi av dataen din med grafer 📈',
    speakers: 'Einar Afiouni, Sara Hjelle',
    type: 'Annet',
  },
  {
    timeKey: '15:55',
    time: '15:55-16:15',
    location: 'Lesesal 1',
    title: 'Kampen om å redde liv',
    speakers: 'Sebastian Olafsson',
    type: 'Soft skills',
  },
  {
    timeKey: '15:55',
    time: '15:55-16:15',
    location: 'Foredragsrommet',
    title: 'Hva er kompleksitet? || Å herske og bli hersket med',
    speakers: 'Emil Danielsen, Ane Mengshoel',
    type: 'Tech(tungt)',
  },
]

export default schedule
