name: Lag CodePush 🚀

on:
  workflow_dispatch:
    inputs:
      targetVersion:
        description: 'Versjonsnavn fra AppCenter, feks: 1.0.0-<branchname>'
        required: true
        default: '1.0.0-appcenter-script'
jobs:
  build_codepush:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: |
          echo "Target version: ${{ github.event.inputs.targetVersion }}"

      - name: NPM install CI
        run: npm ci

      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +%d%m%H%M)"

      - name: Bygg CodePush
        run: |
          npx appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
          npx appcenter codepush release-react -a leif.erik.bjorkli-BEKK.no/RNSkolenApp -d Staging -t ${{ github.event.inputs.targetVersion }} --description "${{ github.event.inputs.targetVersion }}-${{ steps.timestamp.outputs.timestamp }}"
          npx appcenter codepush release-react -a leif.erik.bjorkli-BEKK.no/RNSkolenApp-Android -d Staging -t ${{ github.event.inputs.targetVersion }} --description "${{ github.event.inputs.targetVersion }}-${{ steps.timestamp.outputs.timestamp }}"
