name: Lag CodePush 🚀

on: workflow_dispatch
jobs:
  build_codepush:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: |
          echo "Target version: ${{ github.head_ref }}"

      - name: NPM install CI
        run: npm ci

      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +%d%m%H%M)"

      - name: Bygg CodePush
        run: |
          npx appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
          npx appcenter codepush release-react -a leif.erik.bjorkli-BEKK.no/RNSkolenApp -d Staging -t ${{ github.head_ref }} --description "${{ github.head_ref }}-${{ steps.timestamp.outputs.timestamp }}"
          npx appcenter codepush release-react -a leif.erik.bjorkli-BEKK.no/RNSkolenApp-Android -d Staging -t ${{ github.head_ref }} --description "${{ github.head_ref }}-${{ steps.timestamp.outputs.timestamp }}"
